spring:
    application:
      name: telegram-bot

telegram:
  bot:
    username: "LMSdemobot"
    token: "take your own token from botfather"
#  webhook:
#    url: "https://myserver.com/telegram/webhook"
